### Introduction to Python
#### Date: Sep 06,2023
#### Submission must be made through Github
You are required to complete all tasks correctly (or almost correctly) . You are free to use any material (lecture, Stackoverflow etc.) except full solutions but you should first try to figure them out on your own. We use an nbgrader for partially autograding the assignments. Please DO NOT delete or copy cells. You can add new cells but your solutions should go into the designated cells. 

`range()` practice

1 . Print the numbers between 60 and 69 inclusive.

In [72]:
for number in range(60,70):
    print(number)
# raise NotImplementedError()

60
61
62
63
64
65
66
67
68
69


2 . Read numbers until 0 and print their mean and standard deviation without using a list.

In [73]:
# YOUR CODE HERE
import math
number  = None
mean = 0
standard_deviation = 0
cumulative_sum = 0
cumulative_square_sum = 0
number_count = 0

while number != 0:
    number = int(input('Enter number: '))
    cumulative_sum += number
    cumulative_square_sum += number**2
    number_count += 1

number_count -= 1

if number_count > 0: 
    mean = cumulative_sum / number_count
    standard_deviation = ((cumulative_square_sum/number_count) - mean**2)**(0.5)

print(f'''mean: {mean}''')
print(f'''standard deviation: {standard_deviation}''')
# raise NotImplementedError()

Enter number:  1
Enter number:  5
Enter number:  8
Enter number:  0


mean: 4.666666666666667
standard deviation: 2.8674417556808747


##### Lists
3 . Print the odd numbers from this list. `l = [2, 3, -2, -7, 0, 2, 3]`

In [74]:
# YOUR CODE HERE
l = [2, 3, -2, -7, 0, 2, 3]
is_odd = lambda number: number % 2 != 0
for number in l:
    if is_odd(number):
        print(number)
# raise NotImplementedError()

3
-7
3


##### Functions
4 . Write a function that takes an integer parameter `(N)` and returns a list of the first `N` prime numbers starting from 2.

In [75]:
# YOUR CODE HERE
def is_prime(number):
    if number <= 1:
        return False
    if number <= 3:
        return True
    if number % 2 == 0 or number % 3 == 0:
        return False
    i = 5
    while i**2 <= number:
        if number % i == 0 or number % (i + 2) == 0:
            return False
        i += 6
    return True

def get_n_primes(N):
    prime_numbers = []
    num = 2
    while len(prime_numbers) < N:
        if is_prime(num):
            prime_numbers.append(num)
        num += 1
    return prime_numbers
# raise NotImplementedError()

In [76]:
assert(get_n_primes(3) == [2, 3, 5])
assert(get_n_primes(0) == [])

5. Write a function that takes an integer parameter (N) and returns the Nth Fibonacci number.

 The Fibonacci series is defined as:

$$
F_n = F_{n-1} + F_{n-2} \text{ for } n>1\\
F_0 = 0\\
F_1 = 1
$$

The first few elements of the Fibonacci series are 0, 1, 1, 2, 3, 5, 8, 13 etc.

Raise a `ValueError` if $N<0$.


In [77]:
# YOUR CODE HERE
def get_nth_fibonacci(N):
    if N<0:
        raise ValueError('Invalid input');
    if N == 0:
        return 0
    elif N == 1:
        return 1

    previous = 0
    current = 1
    for _ in range(2, N + 1):
        next = previous + current
        previous = current
        current = next

    return current
    
# raise NotImplementedError()

In [78]:
assert(get_nth_fibonacci(0) == 0)
assert(get_nth_fibonacci(1) == 1)
assert(get_nth_fibonacci(2) == 1)
assert(get_nth_fibonacci(5) == 5)
assert(get_nth_fibonacci(7) == 13)

try:
    get_nth_fibonacci(-2)
except ValueError:
    pass
else:
    AssertionError("TEST FAILS. Negative index should raise a ValueError.")

6 . Create a function that take a list and a predicate (function with boolean return value) as parameters and returns a new list of those elements which the predicate return True. A predicate is a function that takes one element and return `True` or `False`, for example `is_even`, `is_prime`. If you implemented The following tests should run.


In [79]:
# YOUR CODE HERE
def filter_list(l, predicate):
    return [x for x in l if predicate(x)]
# raise NotImplementedError()

In [80]:
l1 = [1, 2, 3, 4, 19, 35, 11]
l2 = [1, 4, 9, 16, 25]
assert(filter_list(l1, is_odd) == [1, 3, 19, 35, 11])
assert(filter_list(l1, is_prime) == [2, 3, 19, 11])
assert(filter_list(l2, is_prime) == [])

7.  Reduce is a function that applies a two argument function against an accumulator and each element in the sequence (from left to right) to reduce it to a single value. If no initial value is provided, the accumulator is initialized with the return value of the function run on the first two elements of the sequence.

```
reduce([1, 2, 3], product) ---> 6
reduce([1, 2, 3], product, accumulator=10) ---> 60
reduce(["foo", "bar"], string_addition) ---> "foobar"
reduce(["foo", "bar"], string_addition, accumulator="hello") ---> "hellofoobar"
```

In [81]:
# YOUR CODE HERE
def reduce(iterable,func, initial=None):
    iterator = iter(iterable)
    if initial is None:
        try:
            accumulator = next(iterator)
        except StopIteration:
            raise TypeError("Type Error")
    else:
        accumulator = initial

    for item in iterator:
        accumulator = func(accumulator, item)

    return accumulator

add = lambda a,b: a+b
string_len_add = lambda accumulator, str: accumulator + len(str)

# raise NotImplementedError()

In [82]:
l1 = [1, 2, -1, 5]
l2 = ["foo", "bar", "hello"]

assert(reduce(l1, add) == 7)
assert(reduce(l1, add, 10) == 17)
assert(reduce(l2, string_len_add, 0) == 11)

8. Use your reduce function for the following operations:

##### a. count the number of odd elements in a list of integers,
##### b. find the maximum of a list of integers,
##### c. find the longest string in list of strings.

``` Test your solutions. ```

In [83]:
# YOUR CODE HERE

count_odd = lambda accumulator, integer:  accumulator + 1 if integer%2 != 0 else accumulator
find_max = lambda accumulator, integer: accumulator if accumulator >= integer else integer
find_longest_str = lambda accumulator, str: accumulator if len(str) < len(accumulator) else str

# raise NotImplementedError()

In [84]:
# YOUR CODE HERE
assert(reduce(l1, count_odd) == 3)
assert(reduce(l1, count_odd) == 3)
assert(reduce(l1, find_max) == 5)
assert(reduce(l2, find_longest_str) == "hello")
# raise NotImplementedError()

9. Create a function that takes a matrix of size NxM and returns the pairwise L2 distance of each row pair.

For input $A^{N \times M}$, the output should be $D^{N \times N}$ where: $D_{i,j} = L_2 (A_i, A_j)$

In [85]:
# YOUR CODE HERE
import numpy as np

def pairwise_row_distance(A):
    A = np.array(A, dtype=float)
    num_rows = A.shape[0]
    D = np.zeros((num_rows, num_rows), dtype=float)
    
    for i in range(num_rows):
        for j in range(num_rows):
            D[i][j] = np.sqrt(np.sum((A[i] - A[j]) ** 2))
    return D

    
is_matrix = lambda M: isinstance(M, np.ndarray) and D.ndim == 2
transpose = lambda M: M.T

# raise NotImplementedError()

In [86]:
D = pairwise_row_distance([[1, 0, 2], [0, 2, 1]])
# should be a matrix
assert is_matrix(D) == True
assert len(D) == 2
assert len(D[0]) == 2
assert D[0][0] == 0
assert abs(D[0][1] - 2.449489742783178) < 1e-3
assert abs(D[1][0] - 2.449489742783178) < 1e-3
assert D[1][1] == 0

# should be symmetric
# assert transpose(D) == D
assert np.array_equal(transpose(D), D)

10 . Object Oriented Programming
 Define a class named `A` with a 'constructor' that takes a single parameter and stores it in an attribute named `value`. Add a `print_value` method to the class. Instantiate the class and call the `print_value` method.

In [87]:
# YOUR CODE HERE
class A:
    def __init__(self, param):
        self.value = param
    def print_value(self):
        print(self.value)

# raise NotImplementedError()

In [88]:
a = A("abc")
a.print_value()

abc


11.  Define a class named `B`, whose `__init__` takes two parameters and stores one in a public attribute and the other in a private attribute named `this_is_public` and `__this_is_private` respectively. Check the class's ``__dict__``  attribute and find out the mangled name of the private attribute.

In [89]:
# YOUR CODE HERE
class B:
    def __init__(self, param1, param2):
        self.this_is_public = param1
        self.__this_is_private = param2
# raise NotImplementedError()

In [90]:
b = B(1, 2)
assert b.this_is_public == 1
try:
    b.__this_is_private
    print("This should not happen.")
except AttributeError:
    print("Failed to access private attribute, this is good :)")

Failed to access private attribute, this is good :)


13 . Inheritance

###### Guess the output without running the cell.

In [91]:
class A(object): pass
class B(A): pass
class C(A): pass
class D(B): pass

a = A()
b = B()
c = C()
d = D()

print(isinstance(a, object))
print(isinstance(b, object))
print(isinstance(a, B))
print(isinstance(b, A))
print(isinstance(d, A))

True
True
False
True
True


In [92]:
print(issubclass(C, object))
print(issubclass(D, B))
print(issubclass(B, D))
print(issubclass(B, B))

True
True
False
True


#### Create a Cat, a Dog, a Fish and a Eagle class.

The animals have the following attributes:

1. cats, dogs and eagles can make a sound (this should be a make_sound function that prints the animals sound),
2. all animals have an age and a number_of_legs attribute,
3. cats and dogs have a fur_color attribute. They can be instantiated with a single color or a list or tuple of colors.

Use inheritance and avoid repeating code. Use default values in the constructors.

In [93]:
# YOUR CODE HERE
class Fish:
    def __init__(self, name="AnonymousFish", age=None, number_of_legs=0):
        self.name = name
        self.age = age
        self.number_of_legs = number_of_legs
        
class Eagle(Fish):
    def __init__(self, name="AnonymousEagle", age=None, number_of_legs=2, sound="screech"):
        super().__init__(name=name, age=age, number_of_legs=number_of_legs)
        self.sound = sound
    def make_sound(self):
        print(self.sound)

class Cat(Eagle):
    def __init__(self, name="AnonymousCat", age=None, fur="", number_of_legs=4, sound="mew"):
        super().__init__(name=name, age=age, number_of_legs=number_of_legs, sound=sound)
        self.fur = fur
        
class Dog(Cat):
    def __init__(self, name="AnonymousDog", age=None, fur="", number_of_legs=4, sound="bark"):
        super().__init__(name=name, age=age, fur=fur, number_of_legs=number_of_legs, sound=sound)
# raise NotImplementedError()

In [94]:
try:
    cat = Cat("Fluffy", age=3, fur="white")
    dog = Dog("Cherry", age=1, fur=("white", "brown", "black"))
    fish = Fish("King")
    eagle = Eagle("Bruce", age=2)
    animals = [cat, dog, fish, eagle]
except Exception as e:
    print(f'Could not initialize an animal: {e}')

#### Numpy basic exercises

Use vectorization and avoid for loops in all exercises. Implement each exercise as a single function.

##### Implement standardization for 2D arrays.

Standardization is defined as:

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

where $\mu$ is the mean of each row and $\rho$ is the standard deviation of each column.

In [95]:
import numpy as np

def standardize(X): 
    # YOUR CODE HERE
    mu = np.mean(X, axis=1)
    sigma = np.std(X, axis=0)
    mu = mu.reshape(-1, 1)
    X_std = (X - mu) / sigma
    return X_std

X_std = standardize(np.array([[1, 2], [2, 3], [1, 2]]))
X_std

array([[-1.06066017,  1.06066017],
       [-1.06066017,  1.06066017],
       [-1.06066017,  1.06066017]])

#### Implement normalization for 2D arrays.

Normalization is defined as:

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

In [96]:
import numpy as np
def normalize(matrix):
    # YOUR CODE HERE
    min_values = np.min(X, axis=0)
    max_values = np.max(X, axis=0)
    normalized_matrix = (matrix - min_values) / (max_values - min_values)

    return normalized_matrix

X = np.arange(6).reshape(2, 3)
X[1, 2] = -5
print(X)
normalize(X)

[[ 0  1  2]
 [ 3  4 -5]]


array([[0., 0., 1.],
       [1., 1., 0.]])

In [97]:
answer = np.array(
    [[0., 0., 1.],
     [1., 1., 0.]]
)
X_norm = normalize(X)
assert np.allclose(X_norm, answer)